### PR TITLE
Sessions new

### PR DESCRIPTION
**Pull request by jjojo**

### CODE REVIEW

**Comment by fippli** [comment]
In `CreateSessionId()`, how do we ensure that the sessionid is unique?

**Comment by jjojo** [comment]
Unique session id's

Session id's are for identifying users of web applications, so they must be unique. The following code shows how to achieve this goal:
```
    func (manager *Manager) sessionId() string {
        b := make([]byte, 32)
        if _, err := io.ReadFull(rand.Reader, b); err != nil {
            return ""
        }
        return base64.URLEncoding.EncodeToString(b)
    }
```
from https://astaxie.gitbooks.io/build-web-application-with-golang/en/06.2.html

Should be unique enough, "assuming that each byte is as probable as any other and rand.Reader is truly random.
You'll get probability (1/256)^32=2^-256 that two generated numbers are the same."
https://groups.google.com/forum/#!topic/golang-nuts/KOIh4rUJRIc

**Comment by fippli** [comment]
Would it be relevant to store all active sessions to compare if its unique? Will that decrease security maybe?

**Comment by jjojo** [comment]
As of now the missions are stored in memory, later I think we can implement a solution where it is saved in the database (had this working previously) and then use the postgres uuid to make sure it gets a unique value. The sessions should also be periodically clear very hour from the database in this case and updated så it won’t be an issue I think

**Pull request merged**
